### ISSUE TITLE
wafer的cos模块是不是有bug？

### ISSUE THREAD

**Issue by yoohan-dex** [tencentyun/wafer2-node-sdk#10]
![image](https://user-images.githubusercontent.com/7565496/33243393-86f02b26-d320-11e7-9d90-03463bb0a3fc.png)
返回的url那个region变成了undefined

然后我看了源码
![image](https://user-images.githubusercontent.com/7565496/33243515-c7db834a-d322-11e7-9a82-add47bb9f422.png)
这个url跟实际的差很多 region map是没有必要的

是有别的用意吗？

**Comment by yoohan-dex** [comment]
哦 我知道了 我下到了最新版 估计是后面cos会多一些地区吧

**Comment by jas0ncn** [comment]
这个是哪里下载的代码呢？

**Comment by yoohan-dex** [comment]
npm 呀 @jas0ncn

**Comment by jas0ncn** [comment]
哦哦，了解了，新版兼容了 COS V5 版本的 API，所以 config.js 里的地域名称需要修改一下，参考：https://cloud.tencent.com/document/product/436/6224 的【适用于 XML API】的地域简称。
![image](https://user-images.githubusercontent.com/3380894/33317043-01be3cca-d471-11e7-8084-6fd74a5897e0.png)

**Comment by bfkkkd** [comment]
按照上面的设置还有不行，提示403，还需要别的权限？
VM2095:2 Failed to load image http://wximg-1254136895.cosgz.myqcloud.com/1511873262825-BkPxiR5lf.png
the server responded with a status of 403 (HTTP/1.1 403 Forbidden) 
From server 14.119.113.163
