### ISSUE TITLE
cos上传之后的返回地址问题

### ISSUE THREAD

**Issue by melon** [tencentyun/wafer2-node-sdk#11]
https://github.com/tencentyun/wafer2-node-sdk/blob/6a69a257fb4cdb9d6eb831ffcb9f7c69f8e2129a/lib/upload/index.js#L126

如果指定了 uploadFolder ， 这个地址是不是应该在域名后面加个 uploadFolder 的文件夹前缀？

另外，可否将各种参数单独返回回来可供用户自定义拼接url？举个例子，比如说有种场景是我希望用https的链接地址，返回的http协议的地址不能满足我的需求。

**Comment by jas0ncn** [comment]
可以理解，下一个版本支持，返回多个参数

**Comment by jas0ncn** [comment]
![image](https://user-images.githubusercontent.com/3380894/33831709-184395ec-deb4-11e7-8233-ff750f737902.png)

更新了新版的 SDK，已经支持返回全部字段。

```bash
npm i wafer-node-sdk@1.2.0 --save
```
