### ISSUE TITLE
nodejs demo修改app,appSecret,host后，使用图片上传，提示上传成功，但是预览无法显示图片，提示403图片无法打开

### ISSUE THREAD

**Issue by bookldk** [tencentyun/wafer2-node-sdk#17]
VM300:2 Failed to load image http://qcloudtest-1255944088.cosgz.myqcloud.com/1516349296633-r1t_vQJHM.jpg
the server responded with a status of 403 (HTTP/1.1 403 Forbidden) 
From server 14.119.113.25

**Comment by jas0ncn** [comment]
到cos控制台设置bucket为共有读私有写即可
