### ISSUE TITLE
独立服务tunnelServerUrl配置的问题

### ISSUE THREAD

**Issue by Bluebang** [tencentyun/wafer2-node-sdk#18]
如果在小程序解决方案里面会分配一个地址给你。按之前你在issues里面说的

> tunnelServerUrl 填写 https://tunnel.ws.qcloud.la，tunnelSignatureKey 随机就行

我用demo测试点了链接，提示链接成功，点发送消息没反应。服务端也没有任何报错，请问是什么问题？

**Comment by Bluebang** [comment]
我用的是云服务器，没有配置域名，是不是这个问题？

**Comment by jas0ncn** [comment]
是的。这个需要配置serverHost。另外需要部署上服务器才能使用，不能在本地调试。
