### ISSUE TITLE
数据库可以考虑不同的环境，使用不同的数据库，而不是限制mysql

### ISSUE THREAD

**Issue by daiqing2009** [tencentyun/wafer2-node-sdk#20]
本地的环境可以使用sqlite，无需安装mysql，前端更快上手

**Comment by jas0ncn** [comment]
多个环境不同数据库会导致迁移和开发成本的提高，并不是一种很好的办法。另外 Node.js 开发不一定完全针对前端，而且后台开发使用 sqlite 并不多，由此带来的解答和资料查询的问题也很难解决。暂时不考虑哈~
