### ISSUE TITLE
关于本地调试，信道问题

### ISSUE THREAD

**Issue by honger05** [tencentyun/wafer2-node-sdk#21]
*** 如果购买了腾讯云小程序解决方案，配置项中 serverHost, tunnelServerUrl, tunnelSignatureKey, qcloudAppId, qcloudSecretId, qcloudSecretKey, wxMessageToken 由腾讯云自动下发到您的开发环境和生产环境上。

我在本地启动 node服务来调试信道

tunnelServerUrl
tunnelSignatureKey

不知道在哪找，在腾讯云管理平台找了好久没看到。

qcloudAppId
qcloudSecretId
qcloudSecretKey

这三个参数倒是找到了。

**Comment by jas0ncn** [comment]
本地调试不能调试信道。引导需要有个回调地址，本地的ip不能作为回调地址。

**Comment by Rockergmail** [comment]
@honger05 请问qcloudAppId, qcloudSecretId, qcloudSecretKey在哪里找到？
