### ISSUE TITLE
腾讯云开发环境，数据库脚本执行问题

### ISSUE THREAD

**Issue by honger05** [tencentyun/wafer2-node-sdk#22]
因为发现腾讯云的 mysql 数据库，并没有执行  npm run initdb 这个命令

在 phpMyAdmin 中没有看见有表结构生成。

请问一下，如何执行数据库脚本

**Comment by jas0ncn** [comment]
有的，默认开通时候就完成了。在cAuth数据库中。如果没有你可以手动用phpmyadmin导入tools里面的cAuth.sql文件。
