### ISSUE TITLE
关于上传服务器的问题

### ISSUE THREAD

**Issue by gegego** [tencentyun/wafer2-node-sdk#23]
测试环境上传服务器后，图片链接为
https://lovestory-1256082311.cos.ap-shanghai.myqcloud.com/1518221435533-rJVKO2iLM.png，而实际返回的链接为
https://lovestory-1256082311.cossh.myqcloud.com/1518221435533-rJVKO2iLM.png，
我看历史记录貌似是特意改的，是不是因为测试环境跟实际环境不同造成的，还是cos服务器的返回有变更出入

**Comment by zyp94021** [comment]
遇到了同样的问题

**Comment by gegego** [comment]
这个问题绕开就行，别理返回的那个imgURL，自己重新定义成cos服务器上的url。
var url = 'http://'+res.data.fileBucket+'-'+res.data.qcloudAppId+'.cos.'+res.data.region+'.myqcloud.com/'+res.data.name

话说，这个服务器代码有超级多的坑，而且没有细节定义的文档，对于不熟悉koajs框架的人来说很难上手，个人还是建议如果想使用koa的框架，还是从零开始学习一下，不行就换成自己熟悉的restful框架根据自己需求重写服务器代码，要自己理解这些代码再修改简直就是折磨。

**Comment by zyp94021** [comment]
解决了，在对象储存权限管理里把默认的公有读私有写改成私有读写在改回来就可以了

**Comment by zyp94021** [comment]
http://www.qingpingshan.com/jb/javascript/357181.html
这里他默认的是私有读写出现这个问题，我默认的是公有读私有写也有这个问题-_-|||，试着改了一下解决了

**Comment by gegego** [comment]
原来是这个坑，但是这个权限对原本链接的访问并没有限制啊，意义何在

**Comment by zyp94021** [comment]
我尝试更改成了私有读写，
https://lovestory-1256082311.cos.ap-shanghai.myqcloud.com/1518221435533-rJVKO2iLM.png这种
和
https://lovestory-1256082311.cossh.myqcloud.com/1518221435533-rJVKO2iLM.png这种
都不能访问了,
开始默认的公有读可能只针对xml api生效对json api无效，来回更改一次后变成了xml和json api都生效了

**Comment by gegego** [comment]
可能那个json url是后来新加的，默认都是私有，跟xml url只有域名级别和几个字节的长度的区别，很难理解这个json url增加的意义

**Comment by zyp94021** [comment]
https://cloud.tencent.com/document/product/436/6052
对象储存历史版本api里有段描述

腾讯云对象存储（COS）服务的 RESTful API 是一种轻量级的，无连接状态的，可以直接通过 http/https 的请求和响应来和腾讯云对象存储（COS）后台进行交互操作的 Web 服务。
JSON API 是腾讯云 COS 服务在推出 XML API 前为用户提供接入使用 COS 的 API 接口，上传域名为 [Region].file.myqcloud.com。JSON API 接口与标准 XML 的 API 底层架构相同，数据互通，可以交叉使用，但是接口不兼容，域名不一致。
腾讯云 COS 的 XML API 服务推出后，推荐您使用 XML API 接口， JSON API 接口日后将保持维护状态，可以正常使用但是不发展新特性。

**Comment by gegego** [comment]
哈哈，所以我理解反了，XML API是重构代码后新的接口，json api是年久失修的旧接口，所以这个代码的问题是他调用了xml api去上传，然后用json api的域名去读取，话说还是特意改成json api的域名。

**Comment by jas0ncn** [comment]
已修正
