### ISSUE TITLE
文件类型判断错误

### ISSUE THREAD

**Issue by DylanMay** [tencentyun/wafer2-node-sdk#31]
在wafer2-node-sdk/lib/upload/ 目录下的index文件里面的fileType判断有问题，会把mp3格式的文件判断为webm格式

**Comment by jas0ncn** [comment]
确认上传到是 mp3 文件吗？sdk 引用的是 file-type 这个库，他不是通过后缀名判断文件格式的，可能你的文件头就是 webm 的，检查一下文件？如果还是有问题可以去 file-type 这个库提一下 issue 哈~
