### ISSUE TITLE
根据getUserInfo新政策，调整代码

### ISSUE THREAD

**Issue by Rockergmail** [tencentyun/wafer2-node-sdk#36]
根据新规则，开发环境，默认获取不了getUserInfo，所以需要调整demo代码。

https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11524128456FDRhq&version=&lang=zh_CN

还有就是我尝试自己在sdk改代码，上传node_modules，没有生效

**Comment by caidows** [comment]
顶一下 保持关注  请尽快完善

**Comment by i3web** [comment]
demo运行的时候，一直是 获取微信用户信息失败，请检查网络状态

**Comment by jas0ncn** [comment]
@i3web 首次登陆要调用 qcloud.login ，可以查看一下 client sdk 的文档：https://github.com/tencentyun/wafer2-client-sdk#%E7%99%BB%E5%BD%95
