### ISSUE TITLE
nodejs自行配置出错，版本问题？

### ISSUE THREAD

**Issue by tent42** [tencentyun/wafer2-node-sdk#39]
我看的流程是下面这个链接里的，很详细，很棒，但是我的还是出了问题
https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2
我腾讯云服务器的nginx要比教程里的高，教程是1.10 我的是1.14 
教程里面给的yum的nodejs源在我服务器上直接被surpport到了版本v10
但是教程里面的node -v是v8.4.0
于是在服务器拷贝好的serve目录下，npm install时，r错误第一次出现，就是下面这个
npm ERR! notarget No matching version found for wafer-node-sdk@^1.4.1
我还以是不是对node版本有要求，于是又卸载并且yum clean all，重新安装了nodejs官网的二进制v8.4.0做了软链接到bin里。
这次node -v和教程里面一样了，都是v8.4.0 npm教程里没看到，我的是5.3.0
但是npm ERR! notarget No matching version found for wafer-node-sdk@^1.4.1 这个错误依然出现
我看在咱们这个node-sdk里，版本也确实已经迭代到了1.4.1
不知道问题出现在哪里，还望大佬能给方法让我继续摸索 :)
感激不尽！

**Comment by jas0ncn** [comment]
首先建议更新一下 Node.js 版本，然后建议使用官方的 npm 源，不要使用淘宝的 npm，刚刚查了一下，淘宝的 npm 也更新了。
