### ISSUE TITLE
不支持mongodb？

### ISSUE THREAD

**Issue by choelea** [tencentyun/wafer2-node-sdk#4]
SDK 暴露了 Mysql 的链接； 意思就是天然支持mysql， 不支持mongodb？ 
文档不够详细

**Comment by jas0ncn** [comment]
是的，账户储存这种关联型的数据适合存储在关系型数据库中，所以使用的 MySQL，连接 MongoDB 可以自己开发哈~

文档哪些地方不够详细呢？能否更清楚的说明一下，我们这里能继续完善。

**Comment by choelea** [comment]
我看见会话表里面蛮多都是JSON的字段，mysql5.7 才开始支持的吧？  这个个人感觉最好留个SDK使用者自由空间。  连MongoDB自己开发, 这个SDK是支持的？ 具体该怎么做？ 还是不能用这个SDK？
另外，wafer-node-sdk 是早起的版本，还在维护升级吗？如果没有，应该给用户提示下啊

**Comment by jas0ncn** [comment]
维护的，这是两个版本。
JSON 是转成字符串存在数据库中的，所以和 MySQL 版本关系不大。
因为我们的环境是直接提供了 MySQL，所以这个 SDK 直接连接了 MySQL。MongoDB 的用法就是平常的用法，不需要特殊的操作哈。但是如果你想把会话信息存在 MongoDB 中的话，目前确实是没办法的。

**Comment by choelea** [comment]
了解了，谢谢这么及时的回复哈。

**Comment by jas0ncn** [comment]
不客气哈。感谢使用腾讯云微信小程序解决方案~
