### ISSUE TITLE
新版wafer2-node-sdk刷新用户信息的问题

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-node-sdk#40]
在测试wafer2-node-sdk 1.4.1版本时发现，初次登录时的微信昵称会一直存在数据库里，后续即使更改了微信昵称，进行qcloud.login()/qcloud.loginWithCode()操作都不能更新用户信息。

**Comment by jas0ncn** [comment]
qcloud.login 是会更新用户信息的

**Comment by yuzifu** [comment]
@jas0ncn 初次登录后，我把微信的昵称改了，删除小程序再次进入结果小程序（使用opendata组件显示用户信息）还是显示之前的昵称，数据库里也还是之前的昵称，已再次确认过。
