### ISSUE TITLE
wafer2-node-sdk拿到的昵称有可能是乱码

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-node-sdk#41]
有两种模板消息发至服务号，都含有昵称字段。
其中一种模板消息的昵称从数据库里取的，在服务号收到消息里昵称显示正常。
另一种模板消息的昵称是从ctx.state.$wxInfo.userinfo里取的，如果用户昵称包含有表情的话，会有一定的概率出现乱码（黑色方块，中间是问号）。

**Comment by jas0ncn** [comment]
服务器是使用你自己的吗？乱码的是 emoji 表情，需要设置 MySQL 的编码为 utf8mb4

**Comment by yuzifu** [comment]
@jas0ncn 从数据库里读取的昵称是正常的，且编码为utf8mb4__unicode_ci。而wafer2-node-sdk解密出来的反而有问题。
