### ISSUE TITLE
如何支持mysql 5.6版本

### ISSUE THREAD

**Issue by xinconan** [tencentyun/wafer2-node-sdk#42]
我看[自动部署文档](https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2)中说sdk只支持5.7的MySQL，如何支持5.6版本呢？

**Comment by jas0ncn** [comment]
MySQL 5.6 不支持 utf8mb4，如果使用 5.6 存不了昵称里的 emoji 表情。其他的没有影响
