### ISSUE TITLE
新用户首次登录，在authorization方法中出现异常

### ISSUE THREAD

**Issue by kosisiyo** [tencentyun/wafer2-node-sdk#46]
wafer-node-sdk\lib\auth\index.js

原代码：

    // 如果只有 code 视为仅使用 code 登录
    if (code && !encryptedData && !iv) {
        return getSessionKey(code).then(pkg => {
            const { openid, session_key } = pkg
            // 生成 3rd_session
            const skey = sha1(session_key)

            return AuthDbService.getUserInfoByOpenId(openid).then(userinfo => {
                 **wxUserInfo = JSON.parse(userinfo.user_info)**

                return AuthDbService.saveUserInfo(wxUserInfo, skey, session_key)
                .then(userinfo => ({
                    loginState: LOGIN_STATE.SUCCESS,
                    userinfo: {
                        userinfo: wxUserInfo,
                        skey: userinfo.skey
                    }
                }))
            })
        })
    }

这一句在新用户初次登录时，从cSessionInfo表查回的信息必然为空，导致JSON.parse抛出异常

此处建议修改为：

                const wxUserInfo = {'openId':openid}
                if (userinfo !== undefined){
                    if ('user_info' in userinfo){
                        wxUserInfo = JSON.parse(userinfo.user_info)
                    }
                }

此代码修改已经验证。

**Comment by jas0ncn** [comment]
初次登录的时候一定要有 encryptedData 的，不能单单使用 code 登录
