### ISSUE TITLE
上传文件的接口感觉有问题每次生成的imagekey都是扩展名麻烦尽快修正

### ISSUE THREAD

**Issue by xanhf** [tencentyun/wafer2-node-sdk#47]
const imgKey = `${Date.now()}-${shortid.generate()}` + resultType.ext ? `.${resultType.ext}` : ''

**Comment by jas0ncn** [comment]
感谢提醒！已经修复：https://github.com/tencentyun/wafer2-node-sdk/commit/d4bf5b0f30756c112c445a741808a55363b4efe8
请更新 wafer-node-sdk 到 1.4.5 版本
