### ISSUE TITLE
信道接口是不是存在安全漏洞?

### ISSUE THREAD

**Issue by fanhualei** [tencentyun/wafer2-node-sdk#48]
简单的看了一下源代码， 信道接口是不是存在安全漏洞?

// 创建信道，需要给定后台服务地址
var tunnel = this.tunnel = new qcloud.Tunnel('https://199447.qcloud.la/tunnel');

如果知道 rul，就可以向这个地址发送模拟数据？

**Comment by jas0ncn** [comment]
您可以测试一下，不可以的。目前的最佳实践是每次都会向信道服务器请求一个 tunnel id，而信道服务器每次推送消息也会有 tunnel id，没有是不认的
