### ISSUE TITLE
上传wafer2代码到生产环境部署总是失败，找不到'koa'模块

### ISSUE THREAD

**Issue by oldpotter** [tencentyun/wafer2-node-sdk#5]
![wx20171026-123444](https://user-images.githubusercontent.com/13828653/32035202-2774ed28-b9dd-11e7-9011-74ddaf968046.png)
node_modules已经在本地安装无错。
相同代码上传测试环境没有问题。

**Comment by jas0ncn** [comment]
您好，目前已经上线了生产环境安装依赖的功能，您登录一下控制台，生产环境里面有个安装依赖的选项了。
![image](https://user-images.githubusercontent.com/3380894/32097185-43ba0fee-bace-11e7-9ca6-39eed65a39c2.png)
