### ISSUE TITLE
生产环境上传图片拿到imageKey是扩展名

### ISSUE THREAD

**Issue by LYnnProspery** [tencentyun/wafer2-node-sdk#52]
wafer-node-sdk 已升级到 1.4.5，问题依然存在

**Comment by LYnnProspery** [comment]
确认，为正确代码，结果依然是imageKey为空
![image](https://user-images.githubusercontent.com/18085369/43778682-ec8328c8-9a88-11e8-906d-08073735aef7.png)
这期间为 调整uploadFolder参数的结果，但是个人感觉 无论路径层级，返回的imageKey为空都是有问题的。但是目前没有定位到问题
个人的cos配置
```
cos: {
        region: 'ap-beijing',
        // Bucket 名称       
        fileBucket: 'miss',
        // 文件夹
        uploadFolder: 'miss',

        SecretId: '###',
        SecretKey: '###',
    }
```
测试环境 ok，生产环境会出现此问题。

**Comment by jas0ncn** [comment]
依赖是线上安装的还是打包的本地 node_modules 呢？

**Comment by LYnnProspery** [comment]
已解决 感谢
