### ISSUE TITLE
tunnelServerUrl 和  tunnelSignatureKey

### ISSUE THREAD

**Issue by choelea** [tencentyun/wafer2-node-sdk#6]
如果没有购买小程序解决方案， 我改如何获取这两个东西呢？我单独购买的腾讯云服务器。（其实当时就是想试试小程序，当时还没有什么方案）

**Comment by jas0ncn** [comment]
`tunnelServerUrl` 填写 `https://tunnel.ws.qcloud.la`，`tunnelSignatureKey` 随机就行
